/**
 * Constants & Initial Data for Community Shield (ประชาอารักษ์)
 * Community: ชุมชนวัดเทวราชกุญชร เขตดุสิต ริมแม่น้ำเจ้าพระยา กรุงเทพมหานคร
 */

import {
  AreaRiskMetadata,
  HouseholdAccessMetadata,
  Household,
  WaterSensorReading,
  RescuePlan,
  PreparationChecklistItem,
  SimulationTimelineStep,
} from '../types';

export const COMMUNITY_INFO = {
  nameTh: 'ชุมชนวัดเทวราชกุญชร',
  districtTh: 'เขตดุสิต กรุงเทพมหานคร',
  riverfront: 'ริมแม่น้ำเจ้าพระยา (อยู่นอกแนวคันกั้นน้ำถาวร)',
  contactPhone: '02-243-5311-5 (ฝ่ายพัฒนาชุมชนและสวัสดิการสังคม เขตดุสิต)',
  meetingPoint: 'ลานหน้าวัดเทวราชกุญชรวรวิหาร',
  primaryHospital: 'โรงพยาบาลวชิรพยาบาล (คณะแพทยศาสตร์วชิรพยาบาล ม.นวมินทราธิราช)',
  secondaryHospital: 'ศูนย์บริการสาธารณสุข 6 สโมสรวัฒนธรรมหญิง',
  floodHistory: 'เหตุการณ์น้ำทะเลหนุนสูงและน้ำเหนือหลาก ตุลาคม 2567',
};

// 1. Dual Status Color Mappings
export const AREA_RISK_MAP: Record<string, AreaRiskMetadata> = {
  normal: {
    level: 'normal',
    labelTh: 'ระดับปกติ',
    colorHex: '#10B981', // Emerald-500
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    description: 'ระดับน้ำอยู่ในลำน้ำ ไม่ส่งผลกระทบต่อทางเดินชุมชน',
  },
  watch: {
    level: 'watch',
    labelTh: 'เฝ้าระวัง',
    colorHex: '#F59E0B', // Amber-500
    badgeBg: 'rgba(245, 158, 11, 0.15)',
    description: 'ระดับน้ำเริ่มสูงขึ้น ตลิ่งต่ำเริ่มมีน้ำซึม',
  },
  high_risk: {
    level: 'high_risk',
    labelTh: 'ความเสี่ยงสูง / เตรียมพร้อม',
    colorHex: '#F97316', // Orange-500
    badgeBg: 'rgba(249, 115, 22, 0.15)',
    description: 'น้ำเอ่อท่วมตรอกซอกซอยระดับต่ำ สะพานไม้เริ่มได้รับผลกระทบ',
  },
  critical: {
    level: 'critical',
    labelTh: 'วิกฤต / เร่งด่วน',
    colorHex: '#EF4444', // Red-500
    badgeBg: 'rgba(239, 68, 68, 0.15)',
    description: 'น้ำท่วมสูงเกิน 40 ซม. ทางเดินหลักถูกตัดขาด ต้องอพยพทันที',
  },
};

export const HOUSEHOLD_ACCESS_MAP: Record<string, HouseholdAccessMetadata> = {
  confirmed_safe: {
    status: 'confirmed_safe',
    labelTh: 'ยืนยันปลอดภัย / เข้าถึงได้',
    colorHex: '#10B981',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    description: 'ได้รับการติดต่อแล้ว สภาพบ้านปลอดภัย ทางเข้าออกใช้งานได้',
  },
  followup_needed: {
    status: 'followup_needed',
    labelTh: 'ต้องติดตาม / ยังไม่ยืนยัน',
    colorHex: '#F59E0B',
    badgeBg: 'rgba(245, 158, 11, 0.15)',
    description: 'ยังไม่สามารถติดต่อได้ หรือไม่มีช่องทางออนไลน์ ต้องส่งทีมเดินตรวจ',
  },
  hard_to_access: {
    status: 'hard_to_access',
    labelTh: 'เข้าถึงยาก',
    colorHex: '#F97316',
    badgeBg: 'rgba(249, 115, 22, 0.15)',
    description: 'ซอยหน้าบ้านน้ำท่วมสูง มีสิ่งกีดขวาง หรือสะพานไม้ชำรุด',
  },
  critical_help_needed: {
    status: 'critical_help_needed',
    labelTh: 'ต้องการความช่วยเหลือเร่งด่วน',
    colorHex: '#EF4444',
    badgeBg: 'rgba(239, 68, 68, 0.15)',
    description: 'มีผู้ป่วยติดเตียง ออกซิเจนจำกัด หรือระดับน้ำถึงตัวบ้าน',
  },
};

// 2. Initial Water Sensor Reading Series (Killer Demo Dataset)
export const INITIAL_SENSOR_READINGS: WaterSensorReading[] = [
  {
    id: 'READ_01',
    timestamp: '20:00',
    timeMinutes: 0,
    actualLevelMeters: 0.42,
    forecastLevelMeters: null,
    rateOfRiseMetersPerHour: 0.26,
    rainfallMmPerHour: 35.0,
    batteryPercent: 94,
    signalQuality: 'good',
    isAlertThresholdExceeded: false,
  },
  {
    id: 'READ_02',
    timestamp: '20:30',
    timeMinutes: 30,
    actualLevelMeters: 0.55,
    forecastLevelMeters: null,
    rateOfRiseMetersPerHour: 0.30,
    rainfallMmPerHour: 42.0,
    batteryPercent: 93,
    signalQuality: 'good',
    isAlertThresholdExceeded: false,
  },
  {
    id: 'READ_03',
    timestamp: '21:00',
    timeMinutes: 60,
    actualLevelMeters: 0.72,
    forecastLevelMeters: 0.72,
    rateOfRiseMetersPerHour: 0.34, // +0.17m in 30min
    rainfallMmPerHour: 55.0,
    batteryPercent: 91,
    signalQuality: 'good',
    isAlertThresholdExceeded: true, // Above 0.70m warning
  },
  {
    id: 'READ_04',
    timestamp: '21:30',
    timeMinutes: 90,
    actualLevelMeters: null,
    forecastLevelMeters: 0.84, // AI Forecast
    rateOfRiseMetersPerHour: 0.32,
    rainfallMmPerHour: 48.0,
    batteryPercent: 90,
    signalQuality: 'good',
    isAlertThresholdExceeded: true,
  },
  {
    id: 'READ_05',
    timestamp: '22:00',
    timeMinutes: 120,
    actualLevelMeters: null,
    forecastLevelMeters: 1.00, // Critical threshold reached!
    rateOfRiseMetersPerHour: 0.32,
    rainfallMmPerHour: 30.0,
    batteryPercent: 89,
    signalQuality: 'good',
    isAlertThresholdExceeded: true,
  },
];

// 3. 16 Community Households (from build_community.py layout)
export const INITIAL_HOUSEHOLDS: Household[] = [
  {
    id: 'house-001',
    code: 'A-001',
    title: 'บ้านริมคลอง 1',
    address: '12/1 ซอยวัดเทวราชกุญชร',
    zone: 'Zone A',
    coordinates: { x: -77, y: -3, z: 0 },
    houseType: 'House_Type_A_Gable',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.15,
    residents: [{ id: 'res-1', name: 'นายสมชาย มั่นคง', age: 52 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-002',
    code: 'A-002',
    title: 'บ้านเรือนไทยยกพื้น',
    address: '12/2 ซอยวัดเทวราชกุญชร',
    zone: 'Zone A',
    coordinates: { x: -77, y: 32, z: 0 },
    houseType: 'House_Type_D_Raised_Timber',
    floorElevationMeters: 1.65, // Stilt house! Safe from high water
    alleyElevationMeters: 0.15,
    residents: [{ id: 'res-2', name: 'นางวันดี รักษ์ไทย', age: 67 }],
    digitalAccess: 'feature_phone_call_only',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
    specialNotesTh: 'ใต้ถุนสูง น้ำยังไม่ถึงพื้นเรือน',
  },
  {
    id: 'house-003',
    code: 'A-003',
    title: 'บ้านปั้นหยาซอย 1',
    address: '14 ซอยวัดเทวราชกุญชร',
    zone: 'Zone A',
    coordinates: { x: -77, y: 52, z: 0 },
    houseType: 'House_Type_B_Hip',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.15,
    residents: [{ id: 'res-3', name: 'นายประเสริฐ ดีเลิศ', age: 45 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-004',
    code: 'A-004',
    title: 'บ้านสองชั้นริมเหนือ',
    address: '16 ซอยวัดเทวราชกุญชร',
    zone: 'Zone A',
    coordinates: { x: -77, y: 78, z: 0 },
    houseType: 'House_Type_C_Two_Storey',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.20,
    residents: [{ id: 'res-4', name: 'นางสมจิตต์ บุณยะ', age: 39 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'normal',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-005',
    code: 'A-005',
    title: 'บ้านปั้นหยาซอย 2',
    address: '18 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -29, y: -4, z: 0 },
    houseType: 'House_Type_B_Hip',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.10,
    residents: [{ id: 'res-5', name: 'นายบุญชู แสงทอง', age: 58 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-006',
    code: 'A-006',
    title: 'บ้านสองชั้นซอยกลาง',
    address: '20 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -28, y: 23, z: 0 },
    houseType: 'House_Type_C_Two_Storey',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.10,
    residents: [{ id: 'res-6', name: 'นายวิชัย รัตนกร', age: 63 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-007',
    code: 'A-007',
    title: 'บ้านไม้ใต้ถุนสูงซอย 2',
    address: '22 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -27, y: 44, z: 0 },
    houseType: 'House_Type_D_Raised_Timber',
    floorElevationMeters: 1.65,
    alleyElevationMeters: 0.12,
    residents: [{ id: 'res-7', name: 'นางจำรูญ ศรีสุข', age: 71 }],
    digitalAccess: 'feature_phone_call_only',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-008',
    code: 'A-008',
    title: 'บ้านจั่วซอยตะวันออก 1',
    address: '24 ซอยวัดเทวราชกุญชร',
    zone: 'Zone C',
    coordinates: { x: -5, y: -3, z: 0 },
    houseType: 'House_Type_A_Gable',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.08, // Low terrain!
    residents: [{ id: 'res-8', name: 'นายทวี ชัยมงคล', age: 50 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'high_risk',
    accessStatus: 'followup_needed',
  },
  {
    id: 'house-009',
    code: 'A-009',
    title: 'บ้านไม้ใต้ถุนสูงริมคู',
    address: '26 ซอยวัดเทวราชกุญชร',
    zone: 'Zone C',
    coordinates: { x: -5, y: 23, z: 0 },
    houseType: 'House_Type_D_Raised_Timber',
    floorElevationMeters: 1.65,
    alleyElevationMeters: 0.08,
    residents: [{ id: 'res-9', name: 'นางมาลี ดวงพร', age: 66 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'high_risk',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-010',
    code: 'A-010',
    title: 'บ้านปั้นหยาซอยตะวันออก 2',
    address: '28 ซอยวัดเทวราชกุญชร',
    zone: 'Zone C',
    coordinates: { x: -4, y: 44, z: 0 },
    houseType: 'House_Type_B_Hip',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.09,
    residents: [{ id: 'res-10', name: 'นายอนุชา ศักดา', age: 41 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'high_risk',
    accessStatus: 'followup_needed',
  },
  {
    id: 'house-011',
    code: 'A-011',
    title: 'บ้านจั่วซอยเหนือ',
    address: '30 ซอยวัดเทวราชกุญชร',
    zone: 'Zone D',
    coordinates: { x: -32, y: 79, z: 0 },
    houseType: 'House_Type_A_Gable',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.22,
    residents: [{ id: 'res-11', name: 'นางสายใจ งามพริ้ง', age: 55 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'normal',
    accessStatus: 'confirmed_safe',
  },

  // KILLER DEMO HOUSE A-012: The Critical Case!
  {
    id: 'house-012',
    code: 'A-012',
    title: 'บ้านยายสมจิตร (ผู้ป่วยติดเตียง)',
    address: '32/1 ซอยวัดเทวราชกุญชร (หลังตลาดเก่า)',
    zone: 'Zone C',
    coordinates: { x: -7, y: 80, z: 0 },
    houseType: 'House_Type_C_Two_Storey',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.05, // Very low terrain bottleneck!
    residents: [
      {
        id: 'res-12-elder',
        name: 'นางสมจิตร รัตนประสิทธิ์',
        age: 82,
        isBedridden: true,
        hasChronicIllness: true,
        requiresOxygen: true,
        oxygenTankReserveMinutes: 90, // Crucial limitation: 90 mins oxygen reserve!
        mobilityConstraint: 'ไม่สามารถเคลื่อนไหวได้เอง ต้องใช้เปลสนามและทีมแบกหาม',
      },
      {
        id: 'res-12-carer',
        name: 'นางกรรณิการ์ รัตนประสิทธิ์ (บุตรสาวผู้ดูแล)',
        age: 56,
      },
    ],
    digitalAccess: 'no_phone_offline', // Crucial: No smartphone / no line!
    areaRiskLevel: 'critical', // Zone C in flood path
    accessStatus: 'critical_help_needed', // Needs urgent relay
    specialNotesTh: 'ผู้ป่วยติดเตียง มีถังออกซิเจนสำรองเหลือประมาณ 90 นาที ทางเดินหน้าบ้านเริ่มมีน้ำท่วมขัง 35 ซม. รถพยาบาลเข้าไม่ถึง',
  },

  {
    id: 'house-013',
    code: 'A-013',
    title: 'บ้านปั้นหยาซอยเหนือตะวันออก',
    address: '34 ซอยวัดเทวราชกุญชร',
    zone: 'Zone D',
    coordinates: { x: 22, y: 80, z: 0 },
    houseType: 'House_Type_B_Hip',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.20,
    residents: [{ id: 'res-13', name: 'นายธนา วรพงษ์', age: 48 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'normal',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-014',
    code: 'A-014',
    title: 'บ้านไม้ใต้ถุนสูงฝั่งใต้',
    address: '36 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -77, y: -58, z: 0 },
    houseType: 'House_Type_D_Raised_Timber',
    floorElevationMeters: 1.65,
    alleyElevationMeters: 0.14,
    residents: [{ id: 'res-14', name: 'นายอุดม พรหมมา', age: 70 }],
    digitalAccess: 'feature_phone_call_only',
    areaRiskLevel: 'watch',
    accessStatus: 'confirmed_safe',
  },
  {
    id: 'house-015',
    code: 'A-015',
    title: 'บ้านจั่วฝั่งใต้กลาง',
    address: '38 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -53, y: -58, z: 0 },
    houseType: 'House_Type_A_Gable',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.12,
    residents: [{ id: 'res-15', name: 'นางนิตยา มีสุข', age: 60 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'watch',
    accessStatus: 'followup_needed',
  },
  {
    id: 'house-016',
    code: 'A-016',
    title: 'บ้านสองชั้นหัวมุมใต้',
    address: '40 ซอยวัดเทวราชกุญชร',
    zone: 'Zone B',
    coordinates: { x: -26, y: -60, z: 0 },
    houseType: 'House_Type_C_Two_Storey',
    floorElevationMeters: 0.55,
    alleyElevationMeters: 0.15,
    residents: [{ id: 'res-16', name: 'นายธีรเดช กิตติคุณ', age: 53 }],
    digitalAccess: 'smartphone_online',
    areaRiskLevel: 'normal',
    accessStatus: 'confirmed_safe',
  },
];

// 4. Preparation Window Checklist (4 pillars: People, Area, Resource, Plan)
export const INITIAL_PREPARATION_CHECKLIST: PreparationChecklistItem[] = [
  // People
  {
    id: 'chk-p-01',
    category: 'people',
    titleTh: 'ตรวจสอบสถานะบ้าน A-012 (ผู้ป่วยติดเตียง/ออกซิเจน)',
    descriptionTh: 'ประสานอาสาสมัครลงพื้นที่ตรวจระดับน้ำหน้าบ้านและปริมาณออกซิเจนสำรอง',
    completed: false,
    priority: 'high',
  },
  {
    id: 'chk-p-02',
    category: 'people',
    titleTh: 'ตรวจสอบบ้านกลุ่มเปราะบางที่ไม่มีมือถือ (A-002, A-007, A-014)',
    descriptionTh: 'ส่งผู้นำชุมชนเคาะประตูแจ้งเตือนระดับน้ำทะเลหนุนสูง',
    completed: false,
    priority: 'high',
  },
  // Area
  {
    id: 'chk-a-01',
    category: 'area',
    titleTh: 'ตรวจสะพานไม้ยกระดับซอยเชื่อมคลอง (Zone C)',
    descriptionTh: 'ตรวจสอบความแข็งแรงของเสาค้ำและระดับน้ำที่แตะใต้ท้องสะพาน',
    completed: false,
    priority: 'high',
  },
  {
    id: 'chk-a-02',
    category: 'area',
    titleTh: 'ตรวจสอบจุดระบายน้ำหน้าตลาดชุมชน',
    descriptionTh: 'ตรวจสิ่งกีดขวางทางน้ำไหลลงสู่แม่น้ำเจ้าพระยา',
    completed: true,
    priority: 'medium',
  },
  // Resource
  {
    id: 'chk-r-01',
    category: 'resource',
    titleTh: 'สแตนด์บายทีม Community Team 02 พร้อมเปลสนาม',
    descriptionTh: 'เตรียมทีมอาสา 4 นายพร้อมอุปกรณ์ยกย้ายผู้ป่วย ณ ศูนย์สุขภาพ',
    completed: false,
    priority: 'high',
  },
  {
    id: 'chk-r-02',
    category: 'resource',
    titleTh: 'ตรวจสอบความพร้อมรถพยาบาล EMS ณ จุดรับส่ง B',
    descriptionTh: 'ตรวจสอบรถพยาบาลฉุกเฉินระดับสูงพร้อมอุปกรณ์ช่วยหายใจ',
    completed: true,
    priority: 'high',
  },
  // Plan
  {
    id: 'chk-pl-01',
    category: 'plan',
    titleTh: 'ตรวจสอบความจุศูนย์พักพิง A (วัดเทวราชกุญชร)',
    descriptionTh: 'ความจุ 100 คน / ปัจจุบันรองรับแล้ว 82 คน / คงเหลือ 18 ที่',
    completed: true,
    priority: 'medium',
  },
  {
    id: 'chk-pl-02',
    category: 'plan',
    titleTh: 'จัดเตรียมเส้นทางส่งต่อผู้ป่วยไปยัง รพ.วชิรพยาบาล',
    descriptionTh: 'ประสานเส้นทางจราจรบนถนนหลักไม่ให้น้ำท่วมตัดขาด',
    completed: false,
    priority: 'high',
  },
];

// 5. AI Rescue Plans for House A-012 (The Killer Demo Decision Choice)
export const HOUSE_A012_RESCUE_PLANS: RescuePlan[] = [
  {
    id: 'PLAN_A',
    planType: 'PLAN_A',
    titleTh: 'Plan A — Direct EMS (รถพยาบาลเข้าตรง)',
    subtitleTh: 'บ้าน A-012 ➔ รถ EMS ➔ โรงพยาบาลวชิรพยาบาล',
    descriptionTh: 'ส่งรถพยาบาลกู้ชีพขับตรงเข้าไปรับผู้ป่วยถึงหน้าบ้าน A-012',
    recommended: false,
    feasibilityScore: 15,
    prosTh: ['ขั้นตอนการเคลื่อนย้ายน้อยที่สุด', 'ผู้ป่วยอยู่ในการดูแลของทีม EMS ทันที'],
    consTh: [
      'รถพยาบาลไม่สามารถเข้าซอยได้เนื่องจากซอยกว้างเพียง 2.2 เมตร',
      'ถนนหน้าบ้านมีน้ำท่วมขัง 35 ซม. เสี่ยงต่อการเครื่องยนต์ดับ',
      'อาจทำให้เสียเวลาประเมินหน้างานเกินเวลา 90 นาทีของออกซิเจน',
    ],
    requiredResources: {
      communityVolunteersCount: 0,
      stretcherRequired: false,
      emsAmbulanceRequired: true,
      boatRequired: false,
    },
    relayRoute: {
      startPoint: 'บ้าน A-012',
      finalDestination: 'โรงพยาบาลวชิรพยาบาล',
      totalEstimatedDistanceMeters: 1400,
      estimatedTransitMinutes: 18,
    },
    constraintWarningsTh: [
      '⚠️ ข้อจำกัดวิกฤต: ตรอกซอยแคบเกินขนาดรถพยาบาล และน้ำสูงเกิน clearance รถฉุกเฉิน',
    ],
  },
  {
    id: 'PLAN_B',
    planType: 'PLAN_B',
    titleTh: 'Plan B — Community Medical Relay (แนะนำสูงสุด)',
    subtitleTh: 'บ้าน A-012 ➔ ทีมชุมชนแบกเปลบนสะพานไม้ ➔ จุด Medical Point B ➔ รถ EMS ➔ รพ.',
    descriptionTh: 'ทีมอาสาชุมชน 02 นำเปลสนามเดินเท้าไปรับผู้ป่วยที่บ้าน A-012 ผ่านทางเดินสะพานไม้ยกระดับ มายังจุด Medical Point B (ลานหน้าสุขศาลา/วัดเทวราช) เพื่อส่งต่อให้รถพยาบาลกู้ชีพ',
    recommended: true,
    feasibilityScore: 92,
    prosTh: [
      'สามารถเข้าถึงบ้านในตรอกแคบได้โดยไม่ต้องใช้รถยนต์',
      'ใช้เวลาเดินเท้าบนสะพานไม้เพียง 6-8 นาที ถึงจุดนัดพบรถพยาบาล',
      'สอดคล้องกับกรอบเวลาออกซิเจนสำรอง 90 นาทีอย่างปลอดภัย',
      'รถพยาบาล EMS สแตนด์บายพร้อมถังออกซิเจนและเครื่องช่วยหายใจ ณ จุด B',
    ],
    consTh: [
      'ต้องอาศัยทีมชุมชนที่มีทักษะการยกหามเปลสนาม',
      'ต้องตรวจความแข็งแรงของสะพานไม้ชั่วคราวเป็นระยะ',
    ],
    requiredResources: {
      communityVolunteersCount: 4,
      stretcherRequired: true,
      emsAmbulanceRequired: true,
      boatRequired: false,
    },
    relayRoute: {
      startPoint: 'บ้าน A-012 (ตรอกหลังตลาด)',
      intermediateRelayPoint: 'จุดส่งต่อการแพทย์ Medical Point B (ลานวัดเทวราชกุญชร)',
      finalDestination: 'โรงพยาบาลวชิรพยาบาล',
      totalEstimatedDistanceMeters: 180 + 1300,
      estimatedTransitMinutes: 7 + 12,
    },
    constraintWarningsTh: [
      '✅ ผ่านการตรวจสอบ: สะพานไม้ยกสูงยังปลอดภัย และจุด B พ้นแนวน้ำท่วม',
    ],
  },
  {
    id: 'PLAN_C',
    planType: 'PLAN_C',
    titleTh: 'Plan C — Early Evacuation (อพยพเข้าศูนย์พักพิงชุมชน)',
    subtitleTh: 'บ้าน A-012 ➔ ทีมชุมชน ➔ จุดพักพิง Shelter A (วัดเทวราช)',
    descriptionTh: 'อพยพผู้ป่วยพร้อมครอบครัวเข้าสู่ศูนย์พักพิงชั่วคราวของชุมชนวัดเทวราชกุญชร',
    recommended: false,
    feasibilityScore: 38,
    prosTh: ['อยู่ใกล้ชุมชน ไม่ต้องเดินทางไกลบนถนนใหญ่'],
    consTh: [
      'จุดพักพิง Shelter A มีความจุ 100 คน ปัจจุบันรับแล้ว 82 คน (เหลือเพียง 18 ที่)',
      'ศูนย์พักพิงไม่มีอุปกรณ์ทางการแพทย์ขั้นสูงและไม่มีระบบเติมออกซิเจนทางการแพทย์',
      'ไม่เหมาะกับผู้ป่วยติดเตียงที่มีข้อจำกัดด้านออกซิเจน',
    ],
    requiredResources: {
      communityVolunteersCount: 4,
      stretcherRequired: true,
      emsAmbulanceRequired: false,
      boatRequired: false,
    },
    relayRoute: {
      startPoint: 'บ้าน A-012',
      finalDestination: 'จุดพักพิง Shelter A (วัดเทวราชกุญชร)',
      totalEstimatedDistanceMeters: 220,
      estimatedTransitMinutes: 10,
    },
    constraintWarningsTh: [
      '⚠️ คำเตือน: จุดพักพิงไม่มีอุปกรณ์รองรับผู้ป่วยออกซิเจนระยะยาว',
    ],
  },
];

// 6. Simulation Timeline Steps (The Storyline from 20:00 to 20:32)
export const SIMULATION_TIMELINE_STEPS: SimulationTimelineStep[] = [
  {
    timeLabel: '20:00',
    titleTh: 'ตรวจพบระดับน้ำเริ่มสูงขึ้น',
    descriptionTh: 'เซนเซอร์ตรวจวัดระดับน้ำแม่น้ำเจ้าพระยาได้ 0.42 เมตร อัตราเพิ่ม +0.17 ม./30 นาที ฝนตกปานกลางในพื้นที่',
    waterLevelMeters: 0.42,
    alleyWaterDepthCm: 5,
    blockedRoadNames: [],
    systemAlertMessageTh: 'ระบบตรวจพบระดับน้ำเพิ่มขึ้นต่อเนื่องตามอิทธิพลน้ำทะเลหนุน',
  },
  {
    timeLabel: '20:10',
    titleTh: 'AI Flood Forecast & Preparation Window',
    descriptionTh: 'AI ประเมินว่าระดับน้ำอาจแตะ 1.00 เมตร เวลา 22:00 น. เริ่มนับถอยหลัง Preparation Window 2 ชั่วโมง',
    waterLevelMeters: 0.50,
    alleyWaterDepthCm: 12,
    blockedRoadNames: [],
    systemAlertMessageTh: 'เปิด Preparation Window 2 ชั่วโมง: เริ่มตรวจสอบกลุ่มเปราะบางและจุดระบายน้ำ',
  },
  {
    timeLabel: '20:15',
    titleTh: 'Risk Map ปรับ Zone C เป็นความเสี่ยงสูง',
    descriptionTh: 'พื้นที่ลุ่มต่ำ Zone C ปรับเป็นความเสี่ยงสูง AI ให้เหตุผล: พื้นที่แอ่ง + ประวัติน้ำท่วมซ้ำ + น้ำระบายช้า',
    waterLevelMeters: 0.55,
    alleyWaterDepthCm: 18,
    blockedRoadNames: [],
    systemAlertMessageTh: 'Zone C ความเสี่ยงสูง: แนะนำส่งทีมตรวจสอบครัวเรือนในพื้นที่ลุ่มต่ำ',
  },
  {
    timeLabel: '20:20',
    titleTh: 'สถานการณ์วิกฤต: บ้าน A-012',
    descriptionTh: 'ตรวจพบผู้ป่วยติดเตียง (ยายสมจิตร 82 ปี) ออกซิเจนสำรองเหลือ 90 นาที น้ำหน้าบ้าน 35 ซม. รถ EMS เข้าไม่ถึง',
    waterLevelMeters: 0.65,
    alleyWaterDepthCm: 35,
    activeIncidentCode: 'INC-2024-001',
    blockedRoadNames: ['ซอยหน้าบ้าน A-012'],
    systemAlertMessageTh: 'วิกฤต: ผู้ป่วยติดเตียงออกซิเจนจำกัด ต้องการการช่วยเหลือเร่งด่วน',
  },
  {
    timeLabel: '20:22',
    titleTh: 'AI เสนอ 3 แผนการช่วยเหลือ',
    descriptionTh: 'AI วิเคราะห์การเข้าถึงและเปรียบเทียบ Plan A, Plan B, Plan C แนะนำให้ใช้ Plan B (Community Relay)',
    waterLevelMeters: 0.68,
    alleyWaterDepthCm: 38,
    activeIncidentCode: 'INC-2024-001',
    blockedRoadNames: ['ซอยหน้าบ้าน A-012'],
    systemAlertMessageTh: 'AI แนะนำ Plan B (Community Relay): เดินเปลผ่านสะพานไม้ไปจุด B รอรถ EMS',
  },
  {
    timeLabel: '20:23',
    titleTh: 'เจ้าหน้าที่อนุมัติ Plan B & ออก Task #A-012',
    descriptionTh: 'ผู้บัญชาการเหตุการณ์ตรวจสอบและกด [อนุมัติ Plan B] ระบบส่ง Task ตรงเข้ามือถือทีม Community Team 02',
    waterLevelMeters: 0.70,
    alleyWaterDepthCm: 40,
    activeIncidentCode: 'INC-2024-001',
    activeTaskId: 'TASK-A012',
    blockedRoadNames: ['ซอยหน้าบ้าน A-012'],
    systemAlertMessageTh: 'แผนได้รับการอนุมัติ: มอบหมายงาน Task #A-012 ให้ Community Team 02 ปฏิบัติการ',
  },
  {
    timeLabel: '20:30',
    titleTh: 'ทีมถึงพื้นที่ & ส่ง Field Report',
    descriptionTh: 'ทีม Community Team 02 ถึงบ้าน A-012 รายงานว่าสะพานไม้ทางแยกหลักจมน้ำ ส่งพิกัดและระดับน้ำจริงกลับเข้าระบบ',
    waterLevelMeters: 0.72,
    alleyWaterDepthCm: 45,
    activeIncidentCode: 'INC-2024-001',
    activeTaskId: 'TASK-A012',
    blockedRoadNames: ['ซอยหน้าบ้าน A-012', 'สะพานไม้ทางแยก 2'],
    systemAlertMessageTh: 'ได้รับ Field Report: ระดับน้ำจริง 45 ซม. สะพานไม้ทางแยก 2 จมน้ำ',
  },
  {
    timeLabel: '20:32',
    titleTh: 'การปรับเปลี่ยนเส้นทาง: สลับใช้ทางเลี่ยงยกระดับ',
    descriptionTh: 'ระบบตรวจพบสะพานไม้ถูกตัดขาด จึงปรับเส้นทางให้อ้อมผ่านระเบียงหน้าศูนย์ชุมชน ส่งต่อผู้ป่วยสู่จุด B สำเร็จ',
    waterLevelMeters: 0.74,
    alleyWaterDepthCm: 48,
    activeIncidentCode: 'INC-2024-001',
    activeTaskId: 'TASK-A012',
    blockedRoadNames: ['ซอยหน้าบ้าน A-012', 'สะพานไม้ทางแยก 2'],
    systemAlertMessageTh: 'DYNAMIC REPLANNING: ปรับแผนใช้เส้นทางสำรองเลี่ยงสะพานไม้ที่จมน้ำ นำส่งจุด B สำเร็จ',
  },
];
